# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -gcflags='all=-N -l' -o ./tmp/worker cmd/worker/main.go"
# Binary file yields from `cmd`.
bin = "tmp/worker"
# Customize binary.
full_bin = "dlv exec --accept-multiclient --headless --continue --listen :2346 --api-version 2 ./tmp/worker"
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "vendor", "docker", "migration"]
