version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    command: air -c .air.api.toml
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./:/app
    depends_on:
      - db

  worker:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    command: air -c .air.worker.toml
    env_file:
      - .env
    ports:
      - "2346:2346"
    volumes:
      - ./:/app
    depends_on:
      - db
#    profiles:
#      - worker

  db:
    image: postgres:17-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
