// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	notifications "github.com/Tagliatti/magalu-challenge/notifications"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateNotification provides a mock function with given fields: ctx, createNotification
func (_m *Repository) CreateNotification(ctx context.Context, createNotification *notifications.CreateNotification) (int64, error) {
	ret := _m.Called(ctx, createNotification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.CreateNotification) (int64, error)); ok {
		return rf(ctx, createNotification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.CreateNotification) int64); ok {
		r0 = rf(ctx, createNotification)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notifications.CreateNotification) error); ok {
		r1 = rf(ctx, createNotification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type Repository_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - createNotification *notifications.CreateNotification
func (_e *Repository_Expecter) CreateNotification(ctx interface{}, createNotification interface{}) *Repository_CreateNotification_Call {
	return &Repository_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, createNotification)}
}

func (_c *Repository_CreateNotification_Call) Run(run func(ctx context.Context, createNotification *notifications.CreateNotification)) *Repository_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notifications.CreateNotification))
	})
	return _c
}

func (_c *Repository_CreateNotification_Call) Return(_a0 int64, _a1 error) *Repository_CreateNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateNotification_Call) RunAndReturn(run func(context.Context, *notifications.CreateNotification) (int64, error)) *Repository_CreateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotificationByID provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteNotificationByID(ctx context.Context, id int64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_DeleteNotificationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotificationByID'
type Repository_DeleteNotificationByID_Call struct {
	*mock.Call
}

// DeleteNotificationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Repository_Expecter) DeleteNotificationByID(ctx interface{}, id interface{}) *Repository_DeleteNotificationByID_Call {
	return &Repository_DeleteNotificationByID_Call{Call: _e.mock.On("DeleteNotificationByID", ctx, id)}
}

func (_c *Repository_DeleteNotificationByID_Call) Run(run func(ctx context.Context, id int64)) *Repository_DeleteNotificationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_DeleteNotificationByID_Call) Return(_a0 bool, _a1 error) *Repository_DeleteNotificationByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_DeleteNotificationByID_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *Repository_DeleteNotificationByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindNotificationByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindNotificationByID(ctx context.Context, id int64) (*notifications.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindNotificationByID")
	}

	var r0 *notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*notifications.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *notifications.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNotificationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNotificationByID'
type Repository_FindNotificationByID_Call struct {
	*mock.Call
}

// FindNotificationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Repository_Expecter) FindNotificationByID(ctx interface{}, id interface{}) *Repository_FindNotificationByID_Call {
	return &Repository_FindNotificationByID_Call{Call: _e.mock.On("FindNotificationByID", ctx, id)}
}

func (_c *Repository_FindNotificationByID_Call) Run(run func(ctx context.Context, id int64)) *Repository_FindNotificationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_FindNotificationByID_Call) Return(_a0 *notifications.Notification, _a1 error) *Repository_FindNotificationByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNotificationByID_Call) RunAndReturn(run func(context.Context, int64) (*notifications.Notification, error)) *Repository_FindNotificationByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindNotificationStatusByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindNotificationStatusByID(ctx context.Context, id int64) (*notifications.NotificationStatus, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindNotificationStatusByID")
	}

	var r0 *notifications.NotificationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*notifications.NotificationStatus, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *notifications.NotificationStatus); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notifications.NotificationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNotificationStatusByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNotificationStatusByID'
type Repository_FindNotificationStatusByID_Call struct {
	*mock.Call
}

// FindNotificationStatusByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Repository_Expecter) FindNotificationStatusByID(ctx interface{}, id interface{}) *Repository_FindNotificationStatusByID_Call {
	return &Repository_FindNotificationStatusByID_Call{Call: _e.mock.On("FindNotificationStatusByID", ctx, id)}
}

func (_c *Repository_FindNotificationStatusByID_Call) Run(run func(ctx context.Context, id int64)) *Repository_FindNotificationStatusByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_FindNotificationStatusByID_Call) Return(_a0 *notifications.NotificationStatus, _a1 error) *Repository_FindNotificationStatusByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNotificationStatusByID_Call) RunAndReturn(run func(context.Context, int64) (*notifications.NotificationStatus, error)) *Repository_FindNotificationStatusByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingNotifications provides a mock function with given fields: ctx
func (_m *Repository) ListPendingNotifications(ctx context.Context) ([]notifications.Notification, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingNotifications")
	}

	var r0 []notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]notifications.Notification, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []notifications.Notification); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListPendingNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingNotifications'
type Repository_ListPendingNotifications_Call struct {
	*mock.Call
}

// ListPendingNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) ListPendingNotifications(ctx interface{}) *Repository_ListPendingNotifications_Call {
	return &Repository_ListPendingNotifications_Call{Call: _e.mock.On("ListPendingNotifications", ctx)}
}

func (_c *Repository_ListPendingNotifications_Call) Run(run func(ctx context.Context)) *Repository_ListPendingNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_ListPendingNotifications_Call) Return(_a0 []notifications.Notification, _a1 error) *Repository_ListPendingNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListPendingNotifications_Call) RunAndReturn(run func(context.Context) ([]notifications.Notification, error)) *Repository_ListPendingNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// ListenNotifications provides a mock function with given fields: ctx
func (_m *Repository) ListenNotifications(ctx context.Context) (<-chan notifications.Notification, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListenNotifications")
	}

	var r0 <-chan notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan notifications.Notification, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan notifications.Notification); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListenNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenNotifications'
type Repository_ListenNotifications_Call struct {
	*mock.Call
}

// ListenNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) ListenNotifications(ctx interface{}) *Repository_ListenNotifications_Call {
	return &Repository_ListenNotifications_Call{Call: _e.mock.On("ListenNotifications", ctx)}
}

func (_c *Repository_ListenNotifications_Call) Run(run func(ctx context.Context)) *Repository_ListenNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_ListenNotifications_Call) Return(_a0 <-chan notifications.Notification, _a1 error) *Repository_ListenNotifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListenNotifications_Call) RunAndReturn(run func(context.Context) (<-chan notifications.Notification, error)) *Repository_ListenNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotificationAsSent provides a mock function with given fields: ctx, id
func (_m *Repository) UpdateNotificationAsSent(ctx context.Context, id int64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationAsSent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpdateNotificationAsSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotificationAsSent'
type Repository_UpdateNotificationAsSent_Call struct {
	*mock.Call
}

// UpdateNotificationAsSent is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Repository_Expecter) UpdateNotificationAsSent(ctx interface{}, id interface{}) *Repository_UpdateNotificationAsSent_Call {
	return &Repository_UpdateNotificationAsSent_Call{Call: _e.mock.On("UpdateNotificationAsSent", ctx, id)}
}

func (_c *Repository_UpdateNotificationAsSent_Call) Run(run func(ctx context.Context, id int64)) *Repository_UpdateNotificationAsSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_UpdateNotificationAsSent_Call) Return(_a0 bool, _a1 error) *Repository_UpdateNotificationAsSent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpdateNotificationAsSent_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *Repository_UpdateNotificationAsSent_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
